### PR TITLE
fix: reset args.kwargs before running benchmark suites

### PR DESCRIPTION
**Pull request by Char15Xu**
This pr fixed keyError issue when running different datasets in all files from benchmark/suite.

Relavent issue: #67  bullet point 1

issue: args.kwargs kept values from old dataset.

fIx: reset args.kwargs before running dataset

### CODE REVIEW

**Comment by zenodflow** [comment]
@Char15Xu What is the use of `args.kwargs`? It feels like we need a bigger change for the `args.kwargs` design. It's mysterious why one needs to reset it.

**Comment by Char15Xu** [comment]
Based on my understanding of the original code, it is used in libem/prepare/datasets to parse data from datasets.

**Comment by zenodflow** [comment]
@Char15Xu @daiwaid Instead of relying on the client code to reset the kwargs -- which is really an unknown unknown for them - we should https://github.com/abcsys/libem/blob/b16907cdd5334f915ef585cbf74fc86a2c1db3ff/benchmark/classic/abt_buy.py#L38 do a deep copy of the args here!

**Comment by daiwaid** [comment]
Alternate fix implemented in PR #73.

**Pull request closed without merging**
