### PR TITLE
feat: add duckduckgo search and make it default

### PR DESCRIPTION
**Pull request by daiwaid**
simple duckduckgo search using the langchain tool, some refactoring to separate search-engine-specific code

### CODE REVIEW

**Review by zenodflow — COMMENTED** [review]
Looks good. @daiwaid Did you test the examples/browse.py and see if it still works as expected?

**Comment by zenodflow** [comment]
If browse still works: https://github.com/abcsys/libem/blob/main/examples/browse.py, let's make duckduckgo the default?

**Comment by daiwaid** [comment]
browse.py works and duckduckgo is the default.

**Comment by zenodflow** [comment]
Nice!

**Review by zenodflow — APPROVED** [review]

**Pull request merged**
