### PR TITLE
Bug fix for pricing issue

### PR DESCRIPTION
**Pull request by Char15Xu**
#### What this PR does / why we need it:
This PR updates `model_info` when the model choice changes during matching. This ensures that the correct `model_info` is used for retrieving pricing.

#### Which issue(s) this PR addresses (if any):
 
Addresses #  

#### Does this PR introduce a user-facing change?

```release-note
```

### CODE REVIEW

**Comment by zenodflow** [comment]
Good fix @Char15Xu. How do we calculate the cost for anthropic models?

**Comment by zenodflow** [comment]
@daiwaid Do you think this bug impact our existing results (e.g., the graphs on blog)?

**Comment by daiwaid** [comment]
> @daiwaid Do you think this bug impact our existing results (e.g., the graphs on blog)?

No, all benchmark tests are done by explicitly passing in the currently used model into the `get_cost()` function.

**Comment by Char15Xu** [comment]
> Good fix @Char15Xu. How do we calculate the cost for anthropic models?

The same code is used for anthropic models

**Comment by zenodflow** [comment]
> > Good fix @Char15Xu. How do we calculate the cost for anthropic models?
> 
> The same code is used for anthropic models

I see. @Char15Xu but do we have the cost cache for the anthropic models?

**Comment by Char15Xu** [comment]
> > > Good fix @Char15Xu. How do we calculate the cost for anthropic models?
> > 
> > 
> > The same code is used for anthropic models
> 
> I see. @Char15Xu but do we have the cost cache for the anthropic models?

Sorry, I missed this message. When doing benchmark, anthropic models also use the libem.optimize.cost.openai module. There is not a separate cost cache for anthropic models.

**Comment by zenodflow** [comment]
> > > > Good fix @Char15Xu. How do we calculate the cost for anthropic models?
> > > 
> > > 
> > > The same code is used for anthropic models
> > 
> > 
> > I see. @Char15Xu but do we have the cost cache for the anthropic models?
> 
> Sorry, I missed this message. When doing benchmark, anthropic models also use the libem.optimize.cost.openai module. There is not a separate cost cache for anthropic models.

Should there be one? If so, we should do a future PR for this.

**Review by zenodflow — APPROVED** [review]

**Pull request merged**
